//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DDFootwear.discount {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DiscountServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DiscountService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertDiscountOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteDiscountOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateDiscountOperationCompleted;
        
        private System.Threading.SendOrPostCallback findSizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback viewAllSizesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DiscountService() {
            this.Url = global::DDFootwear.Properties.Settings.Default.DDFootwear_discount_DiscountService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insertDiscountCompletedEventHandler insertDiscountCompleted;
        
        /// <remarks/>
        public event deleteDiscountCompletedEventHandler deleteDiscountCompleted;
        
        /// <remarks/>
        public event updateDiscountCompletedEventHandler updateDiscountCompleted;
        
        /// <remarks/>
        public event findSizeCompletedEventHandler findSizeCompleted;
        
        /// <remarks/>
        public event viewAllSizesCompletedEventHandler viewAllSizesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertDiscount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertDiscount(string disID, double disRate) {
            object[] results = this.Invoke("insertDiscount", new object[] {
                        disID,
                        disRate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertDiscountAsync(string disID, double disRate) {
            this.insertDiscountAsync(disID, disRate, null);
        }
        
        /// <remarks/>
        public void insertDiscountAsync(string disID, double disRate, object userState) {
            if ((this.insertDiscountOperationCompleted == null)) {
                this.insertDiscountOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertDiscountOperationCompleted);
            }
            this.InvokeAsync("insertDiscount", new object[] {
                        disID,
                        disRate}, this.insertDiscountOperationCompleted, userState);
        }
        
        private void OninsertDiscountOperationCompleted(object arg) {
            if ((this.insertDiscountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertDiscountCompleted(this, new insertDiscountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteDiscount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteDiscount(string disID) {
            object[] results = this.Invoke("deleteDiscount", new object[] {
                        disID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteDiscountAsync(string disID) {
            this.deleteDiscountAsync(disID, null);
        }
        
        /// <remarks/>
        public void deleteDiscountAsync(string disID, object userState) {
            if ((this.deleteDiscountOperationCompleted == null)) {
                this.deleteDiscountOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteDiscountOperationCompleted);
            }
            this.InvokeAsync("deleteDiscount", new object[] {
                        disID}, this.deleteDiscountOperationCompleted, userState);
        }
        
        private void OndeleteDiscountOperationCompleted(object arg) {
            if ((this.deleteDiscountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteDiscountCompleted(this, new deleteDiscountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateDiscount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int updateDiscount(string disID, double disRate) {
            object[] results = this.Invoke("updateDiscount", new object[] {
                        disID,
                        disRate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void updateDiscountAsync(string disID, double disRate) {
            this.updateDiscountAsync(disID, disRate, null);
        }
        
        /// <remarks/>
        public void updateDiscountAsync(string disID, double disRate, object userState) {
            if ((this.updateDiscountOperationCompleted == null)) {
                this.updateDiscountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDiscountOperationCompleted);
            }
            this.InvokeAsync("updateDiscount", new object[] {
                        disID,
                        disRate}, this.updateDiscountOperationCompleted, userState);
        }
        
        private void OnupdateDiscountOperationCompleted(object arg) {
            if ((this.updateDiscountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateDiscountCompleted(this, new updateDiscountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/findSize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DiscountRates findSize(string disID) {
            object[] results = this.Invoke("findSize", new object[] {
                        disID});
            return ((DiscountRates)(results[0]));
        }
        
        /// <remarks/>
        public void findSizeAsync(string disID) {
            this.findSizeAsync(disID, null);
        }
        
        /// <remarks/>
        public void findSizeAsync(string disID, object userState) {
            if ((this.findSizeOperationCompleted == null)) {
                this.findSizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindSizeOperationCompleted);
            }
            this.InvokeAsync("findSize", new object[] {
                        disID}, this.findSizeOperationCompleted, userState);
        }
        
        private void OnfindSizeOperationCompleted(object arg) {
            if ((this.findSizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findSizeCompleted(this, new findSizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/viewAllSizes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet viewAllSizes() {
            object[] results = this.Invoke("viewAllSizes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void viewAllSizesAsync() {
            this.viewAllSizesAsync(null);
        }
        
        /// <remarks/>
        public void viewAllSizesAsync(object userState) {
            if ((this.viewAllSizesOperationCompleted == null)) {
                this.viewAllSizesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnviewAllSizesOperationCompleted);
            }
            this.InvokeAsync("viewAllSizes", new object[0], this.viewAllSizesOperationCompleted, userState);
        }
        
        private void OnviewAllSizesOperationCompleted(object arg) {
            if ((this.viewAllSizesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.viewAllSizesCompleted(this, new viewAllSizesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DiscountRates {
        
        private string disIDField;
        
        private double disRateField;
        
        /// <remarks/>
        public string DisID {
            get {
                return this.disIDField;
            }
            set {
                this.disIDField = value;
            }
        }
        
        /// <remarks/>
        public double DisRate {
            get {
                return this.disRateField;
            }
            set {
                this.disRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertDiscountCompletedEventHandler(object sender, insertDiscountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertDiscountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertDiscountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteDiscountCompletedEventHandler(object sender, deleteDiscountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteDiscountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteDiscountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updateDiscountCompletedEventHandler(object sender, updateDiscountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateDiscountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateDiscountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void findSizeCompletedEventHandler(object sender, findSizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findSizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findSizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DiscountRates Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DiscountRates)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void viewAllSizesCompletedEventHandler(object sender, viewAllSizesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class viewAllSizesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal viewAllSizesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591